import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import { ANR_DISPLAY_FIELDS, ANR_FEATURES, DVD_DISPLAY_FIELDS, DVD_FEATURES, normalizeANRAction, normalizeANRFacts, normalizeDVDAction, normalizeDVDFacts } from "../src/commands/anr-dvd-actions.mjs";
import { compileANRFollowup, compileDVDFollowup } from "../src/commands/anr-dvd-followup.mjs";
import { validateWorkflowPlan } from "../src/workflow-plan.mjs";

const anrFacts={as_of:"2026-08-03",consensus_rating:"Overweight",consensus_price_target:225,currency:"USD",rows:[{date:"2026-08-01",firm:"Example Research",analyst:"A. Analyst",rating:"Buy",price_target:240,currency:"USD",change_type:"Upgrade"}],source:"Godel ANR panel"};
const dvdFacts={as_of:"2026-08-03",twelve_month_yield_percent:2.4,indicated_yield_percent:2.5,one_year_growth_percent:4,three_year_growth_percent:3.2,payment_frequency:"Quarterly",rows:[{declaration_date:"2026-07-15",ex_date:"2026-08-15",record_date:"2026-08-16",payable_date:"2026-09-01",amount:0.75,currency:"USD",dividend_type:"Regular Cash"}],source:"Godel DVD panel"};

test("ANR and DVD publish exact documented fields and actions",()=>{assert.equal(ANR_DISPLAY_FIELDS.length,8);assert.deepEqual(ANR_FEATURES,["display","date_range","export"]);assert.equal(DVD_DISPLAY_FIELDS.length,12);assert.deepEqual(DVD_FEATURES,["display","date_range"]);});
test("noisy ANR speech keeps consensus distinct from row targets",()=>{const d=compileANRFollowup("ANR","show consensus raiting and consensus price target");assert.deepEqual(d.actions[0].value,["Consensus Rating","Consensus Price Target"]);});
test("ANR rating history fields and exact dates compose",()=>{const d=compileANRFollowup("ANR","show firm analyst rating price target date upgrades from 2025/01/01 to 2026/08/03");assert.equal(d.actions.length,2);assert.deepEqual(d.actions[1].value,{from:"2025-01-01",to:"2026-08-03"});});
test("ANR corrections supersede and relative history clarifies",()=>{assert.deepEqual(compileANRFollowup("ANR","show rating no sorry show upgrades").actions[0].value,["Upgrade / Downgrade"]);assert.match(compileANRFollowup("ANR","show rating history last year").blockers.join(" "),/exact ISO/);});
test("ANR authoritative context preserves omitted visible fields",()=>{const d=compileANRFollowup({command:"ANR",current_config:{display_fields:["Firm","Rating"]}},"also show price target");assert.deepEqual(d.actions[0].value,["Firm","Rating","Price Target"]);});
test("ANR grounded reads report exact observations without advice",()=>{const d=compileANRFollowup({command:"ANR",grounded_facts:anrFacts},"what is the consensus rating and consensus price target");assert.deepEqual(d.grounded_narration.facts,anrFacts);assert.match(d.grounded_narration.semantics,/no investment inference/);assert.equal(d.ready_for_grounded_narration,true);});
test("ANR missing or corrupt rows never fabricate targets",()=>{for(const grounded_facts of [undefined,{...anrFacts,source:"model"},{...anrFacts,consensus_price_target:-1}]){const d=compileANRFollowup({command:"ANR",grounded_facts},"what is the consensus price target");assert.equal(d.grounded_narration,null);assert.match(d.blockers.join(" "),/will not be invented/);}});
test("ANR investment inference and forecasts fail atomically",()=>{for(const s of ["should i buy based on consensus rating","what will the price target be"]){const d=compileANRFollowup({command:"ANR",grounded_facts:anrFacts},s);assert.ok(d.blockers.length);assert.equal(d.ready_for_grounded_narration,false);assert.equal(d.configure_step_draft,null);}});
test("ANR export remains format unresolved regardless of requested extension",()=>{for(const s of ["export this table","download analyst ratings as csv","export as excel"]){const d=compileANRFollowup("ANR",s);assert.equal(d.actions[0].value,null);assert.match(d.blockers.join(" "),/format is unresolved/);assert.equal(d.configure_step_draft,null);}});
test("noisy DVD speech resolves dates amount frequency and yield",()=>{const d=compileDVDFollowup("DVD","show ex date pay date divident amount payment frequency and trailing yeeld");assert.deepEqual(d.actions[0].value,["12-Month Yield","Payment Frequency","Ex-Date","Payable Date","Amount"]);});
test("DVD exact history range and corrections are strict",()=>{assert.deepEqual(compileDVDFollowup("DVD","show yield history from 2020-01-01 through 2026-08-03").actions[1].value,{from:"2020-01-01",to:"2026-08-03"});assert.deepEqual(compileDVDFollowup("DVD","show ex-date no sorry show payable date").actions[0].value,["Payable Date"]);assert.match(compileDVDFollowup("DVD","show payment history last year").blockers.join(" "),/exact ISO/);});
test("DVD grounded narration reads declared live rows only",()=>{const d=compileDVDFollowup({command:"DVD",grounded_facts:dvdFacts},"when is the ex-date and payable date and how much is the amount");assert.deepEqual(d.grounded_narration.facts,dvdFacts);assert.match(d.grounded_narration.semantics,/no forecast/);assert.equal(d.ready_for_grounded_narration,true);});
test("DVD refuses absent corrupt and forecasted values",()=>{for(const grounded_facts of [undefined,{...dvdFacts,source:"model"},{...dvdFacts,rows:[{...dvdFacts.rows[0],amount:-1}]}]){const d=compileDVDFollowup({command:"DVD",grounded_facts},"what is the amount and ex-date");assert.equal(d.grounded_narration,null);assert.match(d.blockers.join(" "),/will not be invented/);}const f=compileDVDFollowup({command:"DVD",grounded_facts:dvdFacts},"what will the next dividend amount be");assert.match(f.blockers.join(" "),/will not predict/);assert.equal(f.ready_for_grounded_narration,false);});
test("strict fact and action validators reject malformed dates and types",()=>{assert.throws(()=>normalizeANRAction({feature:"date_range",operation:"set",value:{from:"2026-02-30",to:"2026-03-01"}}),/calendar/);assert.throws(()=>normalizeDVDAction({feature:"display",operation:"select",value:["Ex-Date","Ex-Date"]}),/duplicates/);assert.throws(()=>normalizeANRFacts({...anrFacts,rows:[{...anrFacts.rows[0],price_target:"240"}]}),/number/);assert.throws(()=>normalizeDVDFacts({...dvdFacts,twelve_month_yield_percent:"2.4"}),/number/);});
test("one unsupported clause makes compound display non-executable",()=>{const d=compileANRFollowup("ANR","show firm and export as csv");assert.ok(d.actions.length);assert.ok(d.blockers.length);assert.equal(d.configure_step_draft,null);});
test("workflow recognizes ANR and DVD shapes but enables neither",()=>{const base={version:2,failure_policy:"stop_on_any",layout:null};for(const[command,action]of[["ANR",{feature:"display",operation:"select",value:["Firm"]}],["DVD",{feature:"display",operation:"select",value:["Ex-Date"]}]]){const target={mode:"command",command,security:null};assert.throws(()=>validateWorkflowPlan({...base,steps:[{id:`${command.toLowerCase()}-1`,kind:"configure",target,actions:[action],required:true}]}),/schema-valid but not live-enabled/);}});
test("schema records grounded-only no-inference and unresolved export",()=>{const s=JSON.parse(fs.readFileSync(new URL("../catalog/contracts/anr-dvd-nested.schema.json",import.meta.url),"utf8"));assert.equal(s["x-runtime-enabled"],false);assert.equal(s["x-anr-export-format"],"unresolved");assert.match(s["x-grounded-only"],/exact current/);assert.match(s["x-no-inference"],/No investment recommendation/);});
